name: pulmo
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.1.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2023.5.7=py310haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.2.2=h933977f_10
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py310h00ffb61_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - freetype=2.12.1=h546665d_1
  - gettext=0.21.1=h5728263_0
  - glib=2.76.2=h12be248_0
  - glib-tools=2.76.2=h12be248_0
  - graphviz=2.38=hfd603c8_2
  - gst-plugins-base=1.22.0=h001b923_2
  - gstreamer=1.22.0=h6b5321d_2
  - icu=72.1=h63175ca_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipykernel=6.17.1=pyh025b116_0
  - ipython=8.6.0=pyh08f2357_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jupyter_client=7.4.7=pyhd8ed1ab_0
  - jupyter_core=5.0.0=py310h5588dad_0
  - kiwisolver=1.4.4=py310h232114e_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang13=16.0.3=default_h45d3cf4_0
  - libdeflate=1.18=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.76.2=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - liblapack=3.9.0=16_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_0
  - libtiff=4.5.0=h6c8260b_6
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.4=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_4
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.7.1=py310h5588dad_0
  - matplotlib-base=3.7.1=py310h51140c5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.0=hcfcfb64_3
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - ply=3.11=py_1
  - prompt-toolkit=3.0.32=pyha770c72_0
  - psutil=5.9.4=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h1fd54f2_3
  - python=3.10.6=hcf16a7b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pywin32=304=py310h00ffb61_2
  - pyzmq=24.0.1=py310hcd737a0_1
  - qt-main=5.15.8=h7f2b912_10
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sip=6.7.9=py310h00ffb61_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.1=pyhd8ed1ab_0
  - tbb=2021.9.0=h91493d7_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py310h8d17308_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py310h8d17308_0
  - vc=14.3=h3d8a991_9
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zstd=1.5.2=h12be248_6
  - pip:
      - absl-py==1.3.0
      - albumentations==1.3.0
      - amqp==5.1.1
      - ansi2html==1.8.0
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.2.0
      - arrow==1.2.3
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==22.1.0
      - autopep8==2.0.1
      - beautifulsoup4==4.11.1
      - billiard==3.6.4.0
      - black==22.12.0
      - bleach==5.0.1
      - blinker==1.6.2
      - cachecontrol==0.13.1
      - cachetools==5.2.0
      - celery==5.2.7
      - cffi==1.15.1
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - cloudpickle==2.2.0
      - colab==1.13.5
      - commonmark==0.9.1
      - contextlib2==21.6.0
      - contourpy==1.0.6
      - cryptography==41.0.1
      - cssselect==1.2.0
      - customtkinter==5.1.3
      - cv==1.0.0
      - cython==0.29.33
      - darkdetect==0.8.0
      - dash==2.11.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - diazo==1.5.0
      - dill==0.3.6
      - django==1.7.11
      - django-haystack==2.4.1
      - django-hitcounter==0.1.1
      - django-revproxy==0.10.0
      - django-taggit==0.22.2
      - dlai-tools==0.5.7
      - dm-tree==0.1.8
      - docopt==0.6.2
      - efficientnet==1.0.0
      - ephem==4.1.4
      - etils==0.9.0
      - etiquetando==0.1
      - fastjsonschema==2.16.2
      - filelock==3.9.0
      - fire==0.5.0
      - firebase==4.0.1
      - firebase-admin==6.2.0
      - flask==2.2.5
      - flatbuffers==22.10.26
      - fonttools==4.38.0
      - fqdn==1.5.1
      - gast==0.4.0
      - gcloud==0.18.3
      - gdown==4.6.0
      - gitdb==4.0.9
      - gitpython==3.1.29
      - google-api-core==2.11.1
      - google-api-python-client==2.91.0
      - google-auth==2.14.1
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.3.2
      - google-cloud-firestore==2.11.1
      - google-cloud-storage==2.10.0
      - google-crc32c==1.5.0
      - google-pasta==0.2.0
      - google-resumable-media==2.5.0
      - googleapis-common-protos==1.57.0
      - grpcio==1.56.0
      - grpcio-status==1.56.0
      - gspread==5.7.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - h5py==3.7.0
      - html2text==2020.1.16
      - httplib2==0.21.0
      - idna==3.4
      - image-classifiers==1.0.0
      - imageio==2.22.4
      - imgaug==0.4.0
      - imgviz==1.7.2
      - importlib-metadata==5.0.0
      - importlib-resources==5.10.2
      - ipympl==0.9.2
      - ipython-autotime==0.3.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.0
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-core==5.1.0
      - jupyter-events==0.5.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.1
      - jupyter-server==2.0.1
      - jupyter-server-terminals==0.4.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - jwcrypto==1.5.0
      - kaleido==0.2.1
      - keras==2.10.0
      - keras-applications==1.0.8
      - keras-cv==0.4.2
      - keras-preprocessing==1.1.2
      - kombu==5.2.4
      - korean-lunar-calendar==0.3.1
      - labelme==5.2.0.post4
      - labelme2coco==0.2.4
      - libclang==14.0.6
      - lxml==4.9.1
      - markdown==3.4.1
      - markupsafe==2.1.1
      - mistune==2.0.4
      - mpmath==1.3.0
      - msgpack==1.0.5
      - mypy-extensions==0.4.3
      - natsort==8.3.1
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.6
      - nbformat==5.7.0
      - networkx==2.8.8
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numpy==1.23.4
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - object-detection==0.0.3
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.7.0.72
      - opt-einsum==3.3.0
      - pandas==1.5.1
      - pandocfilters==1.5.0
      - pathspec==0.10.3
      - patsy==0.5.3
      - pillow==9.3.0
      - pipreqs==0.4.13
      - plotly==5.11.0
      - pluggy==1.2.0
      - pmdarima==2.0.2
      - prometheus-client==0.15.0
      - promise==2.3
      - proto-plus==1.22.3
      - protobuf==3.19.0
      - pyarrow==10.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyaudio==0.2.13
      - pybboxes==0.1.6
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pycryptodome==3.18.0
      - pydeck==0.8.0
      - pydot==1.4.2
      - pyjwt==2.7.0
      - pymeeus==0.5.12
      - pympler==1.0.1
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - pyqtgraph==0.13.3
      - pyrebase4==4.7.1
      - pyrsistent==0.19.2
      - pyscript==0.2.5
      - pysocks==1.7.1
      - python-graphviz==0.20.1
      - python-json-logger==2.0.4
      - python-jwt==4.0.0
      - pytz==2022.6
      - pytz-deprecation-shim==0.1.0.post0
      - pywavelets==1.4.1
      - pywinpty==2.0.9
      - pyyaml==6.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - qudida==0.0.4
      - redis==4.4.0
      - regex==2023.3.23
      - repoze-lru==0.7
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.10.1
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==12.6.0
      - rich-click==1.6.1
      - rsa==4.9
      - sahi==0.11.13
      - scikit-image==0.19.3
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - seaborn==0.12.1
      - segmentation-models==1.0.1
      - semver==2.13.0
      - send2trash==1.8.0
      - setuptools-git==1.2
      - shapely==2.0.1
      - sklearn==0.0.post1
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - sox==1.4.1
      - statsmodels==0.13.5
      - stemming==1.0.1
      - streamlit==1.18.1
      - sympy==1.12
      - tenacity==8.1.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-addons==0.20.0
      - tensorflow-datasets==4.8.3
      - tensorflow-estimator==2.10.0
      - tensorflow-hub==0.12.0
      - tensorflow-io-gcs-filesystem==0.27.0
      - tensorflow-metadata==1.12.0
      - termcolor==2.1.0
      - terminado==0.17.1
      - terminaltables==3.1.10
      - threadpoolctl==3.1.0
      - tifffile==2022.10.10
      - tinycss2==1.2.1
      - toolz==0.12.0
      - tqdm==4.64.1
      - traitlets==5.7.1
      - typeguard==2.13.3
      - typer==0.4.2
      - typing-extensions==4.4.0
      - tzdata==2022.6
      - tzlocal==4.2
      - uri-template==1.2.0
      - uritemplate==4.1.1
      - urllib3==1.26.12
      - uuid==1.30
      - validators==0.20.0
      - vine==5.0.0
      - watchdog==3.0.0
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - werkzeug==2.2.3
      - whoosh==2.7.4
      - widgetsnbextension==4.0.5
      - wrapt==1.14.1
      - xgboost==1.7.2
      - yarg==0.1.9
      - yellowbrick==1.5
      - zipp==3.10.0

